pipeline {
   /// testing agent
    agent {
      node {
        label 'mobile'
         }
     }

   environment {
     PATH = '/Users/gskdevops/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
   }

   stages {
      stage('display') {
      steps {
        sh 'env'
        sh 'npm install'

     }
  }
  }

}
